'''
Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

n = int(input())
x1, x2 = 1, 2
sum = 0
while x2 <= n:
    if x2 % 2 == 0:
        sum += x2
    x1, x2 = x2, x1 + x2
print(sum)